### ISSUE TITLE
o2image fails on s390x (big endian)

### ISSUE THREAD

**Issue by xnox** [markfasheh/ocfs2-tools#22]
A simple script is used to validate ocfs2-tools

```
#!/bin/sh

set -e

DISK=$AUTOPKGTEST_TMP/disk

cleanup () {
  umount /mnt || true
  [ "$LOOP" ] && losetup -d $LOOP
  rm -f $DISK $DISK.image || true
  service o2cb stop
  sed -i -e 's/^O2CB_ENABLED=.*/O2CB_ENABLED=false/' /etc/default/o2cb
}

trap "cleanup" 0 2 3 15

# configure cluster
HOSTNAME=$(hostname)

cat >/etc/ocfs2/cluster.conf <<EOF
cluster:
        node_count = 1
        name = ocfs2

node:
        ip_port = 7777
        ip_address = 127.0.0.1
        number = 0
        name = $HOSTNAME
        cluster = ocfs2
EOF

# start cluster
sed -i -e 's/^O2CB_ENABLED=.*/O2CB_ENABLED=true/' /etc/default/o2cb
service o2cb restart

# check cluster
echo "=== dlmfs ==="
grep '^ocfs2_dlmfs /dlm' /proc/mounts

echo "=== lsmod ==="
lsmod | grep ocfs2_stack_o2cb

echo "=== o2hbmonitor ==="
pgrep -a o2hbmonitor

# print info
echo "=== o2cluster ==="
o2cluster -r

echo "=== o2cb_ctl ==="
o2cb_ctl -I -n $HOSTNAME

# create test disk
echo "=== losetup ==="
dd if=/dev/zero of=$DISK bs=1M count=200 2>&1
LOOP=$(losetup --find --show $DISK)

# test tools
echo "=== mkfs ==="
mkfs.ocfs2 --cluster-stack=o2cb --cluster-name=ocfs2 $LOOP 2>&1

echo "=== o2image ==="
o2image $LOOP $DISK.image
ls -l $DISK.image

echo "=== fsck ==="
fsck.ocfs2 -f -y $LOOP 2>&1

echo "=== o2cluster ==="
o2cluster -o $LOOP

echo "=== tunefs ==="
tunefs.ocfs2 -L $DISK -N 3 -Q 'Label = %V\nNumSlots = %N\n' $LOOP

echo "=== debugfs ==="
debugfs.ocfs2 -R stats $LOOP

echo "=== o2info ==="
o2info --volinfo $LOOP

echo "=== grow ==="
dd if=/dev/zero of=$DISK bs=1M count=50 seek=200 2>&1
losetup --set-capacity $LOOP
tunefs.ocfs2 -S $LOOP

echo "=== mount ==="
mount $LOOP /mnt
df /mnt

echo "=== mounted ==="
mounted.ocfs2 -d
mounted.ocfs2 -f
```
It fails with segmentation fault at this step:

```
o2image $LOOP $DISK.image
```

on an s390x big endian machine like so:

```
(gdb) run /dev/loop2 /home/ubuntu/disk.image
Starting program: /sbin/o2image /dev/loop2 /home/ubuntu/disk.image
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/s390x-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000000100009aea in ocfs2_set_bit (nr=0, addr=0x0) at bitops.c:52
warning: Source file is more recent than executable.
52		retval = (mask & *ADDR) != 0;
(gdb) bt full
#0  0x0000000100009aea in ocfs2_set_bit (nr=0, addr=0x0) at bitops.c:52
        mask = 1
        retval = 0
        ADDR = 0x0
#1  0x000000010001c782 in ocfs2_image_mark_bitmap (ofs=0x10005b280, blkno=229376) at image.c:250
        ost = 0x10005e000
        bitmap_blk = 7
        bit = 0
#2  0x0000000100007728 in traverse_extents (ofs=0x10005b280, el=0x10007bcc0) at o2image.c:117
        eb = 0x10007bc00
        rec = 0x10007bcd0
        ost = 0x10005e000
        ret = 0
        buf = 0x10007cc00 ""
        i = 0
        j = 229096
#3  0x0000000100008072 in traverse_inode (ofs=0x10005b280, inode=10) at o2image.c:317
        super = 0x10005c8c0
        ost = 0x10005e000
        di = 0x10007bc00
        ret = 0
        dump_type = 1
        buf = 0x10007bc00 "INODE01"
        slot = 2
#4  0x0000000100007524 in traverse_group_desc (ofs=0x10005b280, grp=0x100079400, dump_type=2, bpc=4)
    at o2image.c:76
        ret = 0
        blkno = 10
        i = 2
#5  0x000000010000792e in traverse_chains (ofs=0x10005b280, cl=0x1000780c0, dump_type=2)
    at o2image.c:155
        grp = 0x100079400
        rec = 0x1000780d0
        ret = 0
        buf = 0x100079400 "GROUP01"
        blkno = 8
        i = 0
#6  0x0000000100007f44 in traverse_inode (ofs=0x10005b280, inode=12) at o2image.c:291
        super = 0x10005c8c0
        ost = 0x10005e000
        di = 0x100078000
        ret = 0
        dump_type = 2
        buf = 0x100078000 "INODE01"
        slot = 2
#7  0x0000000100009028 in scan_raw_disk (ofs=0x10005b280) at o2image.c:633
        ost = 0x10005e000
        bits_set = 0
        ret = 51600209153546527
        i = 0
        j = 0
#8  0x00000001000097e8 in main (argc=3, argv=0x3fffffff5c8) at o2image.c:780
        ofs = 0x10005b280
        ret = 0
        src_file = 0x3fffffff81b "/dev/loop2"
        dest_file = 0x3fffffff826 "/home/ubuntu/disk.image"
        open_flags = 0
        raw_flag = 0
        install_flag = 0
---Type <return> to continue, or q <return> to quit---
        interactive = 0
        fd = 1
        c = -1
```

Seems like a null-pointer dereference... or an endianess bug. Specifically something might be of the wrong type, and instead of implicitly accessing the lower portion of an int (like on all little endian arches) the top bits are accessed instead which are all zeros?

**Comment by biger410** [comment]
ocfs2 tools read lots of stuff directly from disk without converting to the endian of cpu using, since the stuff in the disk is in little endian, the tools only works in little endian arch, need modify all those to support big endian.

**Comment by panlinux** [comment]
Why would "the stuff in the disk" be little endian if it was created in the same system, via mkfs just a few steps above?

**Comment by vvidic** [comment]
It seems there is some support for endian conversions, for example:

````
void ocfs2_swap_quota_header(struct ocfs2_disk_dqheader *header)
{
        if (cpu_is_little_endian)
                return;
        header->dqh_magic = bswap_32(header->dqh_magic);
        header->dqh_version = bswap_32(header->dqh_version);
}

````
It just might not be complete?

**Comment by josephhz** [comment]
Yes, for some later features and fixes we have already considered the endian conversions. But unfortunately most original code doesn't.

**Comment by panlinux** [comment]
Does this mean ocfs2 overall doesn't work on s390x, or just some aspect of it?

**Comment by josephhz** [comment]
I'm afraid it should be treated as not work since most of the code doesn't consider endian conversion.
